### ISSUE TITLE
Also add BiopaxToSbgn endpoint

### ISSUE THREAD

**Issue by IgorRodchenkov** [metincansiper/factoid-to-biopax-server#1]
@maxkfranz @jvwong
Shall we simply add here (instead of making a separate web service) the factoid biopax to sbgn converter endpoint?
Igor.

**Comment by maxkfranz** [comment]
I'm fine with that.  This project already uses PAX Tools

**Comment by maxkfranz** [comment]
Maybe we should move this repo to Pathway Commons, though.

**Comment by IgorRodchenkov** [comment]
@maxkfranz,  ok, I moved it to https://github.com/PathwayCommons/factoid-converters and turned into Spring Boot app.
I hope, @metincansiper could still merge pull requests from the PC factoid-converters repo to this one and continue maintaining his biopax converter code.

**Comment by metincansiper** [comment]
@IgorRodchenkov @maxkfranz  sure I can merge PR but as far as I can understand there is a name change in the api. The name of the method used by factoid was "ConvertToOwl". I suppose it is renamed to "json-to-biopax". Therefore, I think that upon merging this [the related line of Factoid] (https://github.com/PathwayCommons/factoid/blob/unstable/src/config.js#L37) may need to be updated as well (and in this case server should be redeployed). What do you think about this?

@IgorRodchenkov if you moved the repository to PC then why do we need to maintain this one as well? If both of the repositories will have the same code is not it more convenient to maintain them from one place?

**Comment by IgorRodchenkov** [comment]
Ok, you don’t have to merge. Just contribute to the new factoid-converters project repo from now.
